export const studyData = [
  {
    text: 'דרישות מוקדמות',
    id: 1,
    name: 'drishot',
    options: [
      { text: 'השכלה תיכונית חלקית', id: '1', name: 'D_partial_high_school_education' },
      { text: 'השכלה תיכונית מלאה', id: '2', name: 'D_full_high_school_education' },
      { text: 'תעודת גמר/מקצוע', id: '3', name: 'D_graduation_certificate' },
      { text: 'טכנאי/ת', id: '4', name: 'D_technician' },
      { text: 'הנדסאי/ת', id: '5', name: 'D_engineer' },
      { text: 'תואר ראשון', id: '6', name: 'D_ba' },
      { text: 'תואר שני', id: '7', name: 'D_masters_dagree' },
      { text: 'תואר שלישי', id: '8', name: 'D_phd' },
      { text: 'פסיכומטרי', id: '9', name: 'D_psychometric' },
    ],
  },
  {
    text: 'מאפיינים מיוחדים',
    id: 2,
    name: 'miuhad',
    options: [
      { text: 'תכניות ייחודיות לבעלי צרכים מיוחדים', id: '1', name: 'CrachimMiuhadim' },
      { text: 'סביבת לימוד מונגשת', id: '2', name: 'Gisha' },
      { text: 'תכניות ייחודיות לציבור הדתי והחרדי', id: '3', name: 'DATI' },
      { text: 'מעונות', id: '4', name: 'PNIMIA' },
      { text: 'תנאי קבלה מיוחדים לבני 30 ומעלה', id: '5', name: 'Ms35' },
      { text: 'מתאים גם לאנשים עובדים', id: '6', name: 'MsTw' },
      { text: 'תכניות ייחודיות לחברה הערבית', id: '7', name: 'MsAr' },
      { text: 'תכניות ייחודיות ליוצאי אתיופיה', id: '8', name: 'MsEt' },
      { text: 'אפיק מעבר של האוניברסיטה הפתוחה', id: '9', name: 'MsRel' },
      { text: 'סלול דו חוגי', id: '10', name: 'MsDo' },
      { text: 'מסלול חד חוגי', id: '11', name: 'MsChad' },
      { text: 'מוכר למימוש פיקדון הקרן לחיילים משוחררים', id: '12', name: 'MsPik' },
      { text: 'מוכר לגמול השתלמות', id: '13', name: 'MsGmul' },
    ],
  },
  {
    text: 'תעודה בסיום',
    id: 2,
    name: 'teuda',
    options: [
      { text: 'תעודת גמר/תעודת מקצוע', id: '1', name: 'T_graduation_certificate' },
      { text: 'טכנאי/ת', id: '2', name: 'T_technician' },
      { text: 'הנדסאי/ת', id: '3', name: 'T_engineer' },
      { text: 'השכלה תיכונית מלאה', id: '4', name: 'T_full_high_school_education' },
      { text: 'תעודת גמר/מקצוע', id: '5', name: 'T_graduation_certificate' },
      { text: 'תואר ראשון', id: '6', name: 'T_ba' },
      { text: 'תואר שני', id: '7', name: 'T_masters_dagree' },
      { text: 'תואר שלישי', id: '8', name: 'T_phd' },
    ],
  },
  {
    text: 'משך מסלול',
    id: 4,
    name: 'meshech',
    options: [
      { text: 'פחות משנה', id: '1', name: 'less_then_year' },
      { text: 'שנה', id: '2', name: 'one_year' },
      { text: 'שנתיים', id: '3', name: 'two_year' },
      { text: 'שלוש שנים', id: '4', name: 'three_year' },
      { text: 'ארבע שנים', id: '5', name: 'four_year' },
      { text: 'חמש עד שש שנים', id: '6', name: 'five_year' },
      { text: 'שבע שנים ומעלה', id: '7', name: 'seven_year' },
    ],
  },
];
export const areaData = [
  { title: 'הנגב והדרום', id: '4', name: 'area' },
  { title: 'חיפה והצפון', id: '2', name: 'area' },
  { title: 'ירושלים וסביבתה', id: '1', name: 'area' },
  { title: 'תל אביב והמרכז', id: '3', name: 'area' },
];
