import Head from 'next/head';


export default function Home() {
	return (
		<div >
			<Head>
				<title>MAIA CLIENT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="main ">
				<h1 className="text-3xl text-center pt-16">
          Welcome to <a href="https://nextjs.org">Maia Project on Next.js!</a>
				</h1>


			</main>
		</div>

	);
}
